### Blogs GET ALL
GET http://localhost:3000/blogs


### Blogs GET ONE
GET http://localhost:3000/blogs/1


### Blogs GET USER BLOGS
GET http://localhost:3000/blogs/user/1

### POST NEW BLOG

POST http://localhost:3000/blogs
Content-Type: application/json

{
  "coverImg":"sample.com",
  "authorId":1,
  "secondImg":"sample2.com",
  "content":"['dummy','dummy2']"
}